### ISSUE TITLE
This is great! Is there a demo? 

### ISSUE THREAD

**Issue by layogtima** [rafCodes/RoboGPT#1]
Have you two deployed it in the wild? Is it on YouTube 👾

**Comment by rafCodes** [comment]
Hi layogtima,

Thank you!

We have used it in the classroom and had people use it to play games.

The video and full website will be up soon

**Comment by rafCodes** [comment]
Hi laygotima,

The video and full website have been added to the readme

**Comment by rafCodes** [comment]
Hi layogtima,

The video and full website have been added to the readme
